import { useEffect, type ReactNode } from "react";
import { ArrowRight, Eye, Megaphone, MapPin, Phone, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { useListFeaturedAdvertisements } from "@workspace/api-client-react";

function SponsoredBadge({ vip = false }: { vip?: boolean }) { return <span className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-[9px] font-black ${vip ? "bg-[#0e2f62] text-white" : "bg-[#f5b916] text-[#0e2f62]"}`}><Sparkles className="h-3 w-3" />{vip ? "إعلان VIP" : "إعلان ممول"}</span>; }
function track(id: number, event: string) { void fetch(`/api/ads/${id}/track`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ event }) }); }

export default function SponsoredPreview() {
  const { data: ads = [], isLoading } = useListFeaturedAdvertisements();
  const previewAds = ads.slice(0, 6);
  useEffect(() => { previewAds.forEach((ad) => track(ad.id, "impression")); }, [previewAds.map((ad) => ad.id).join(",")]);
  return <main className="min-h-[100dvh] bg-[#f7f8fa] pb-24 text-[#0e2f62]" dir="rtl"><header className="sticky top-0 z-10 border-b border-[#0e2f62]/[0.06] bg-white/95 px-4 py-4 backdrop-blur-xl"><div className="mx-auto flex max-w-lg items-center gap-3"><Link href="/" className="flex h-10 w-10 items-center justify-center rounded-full border border-[#dfe5ec] bg-white"><ArrowRight className="h-4 w-4" /></Link><div><p className="text-[11px] font-bold text-[#708198]">معاينة داخل تطبيق العميل</p><h1 className="text-xl font-black">الإعلانات الممولة</h1></div></div></header><div className="mx-auto max-w-lg space-y-6 px-4 pt-5"><section className="rounded-[24px] bg-[#0e2f62] p-5 text-white shadow-[0_12px_28px_rgba(14,47,98,0.16)]"><div className="flex items-start gap-3"><div className="rounded-2xl bg-[#f5b916] p-3 text-[#0e2f62]"><Megaphone className="h-6 w-6" /></div><div><h2 className="text-lg font-black">معاينة الظهور المدفوع</h2><p className="mt-1 text-xs leading-5 text-white/70">إعلانات بارزة ومريحة للعين، مع شارة واضحة حتى تبقى تجربة البحث شفافة للعميل.</p></div></div></section><PreviewSection title="مهنيون مميزون" label="الصفحة الرئيسية"><div className="space-y-3">{isLoading ? <Empty text="جاري تحميل الإعلانات..." /> : previewAds.length === 0 ? <Empty text="لا توجد إعلانات نشطة حاليًا." /> : previewAds.slice(0, 2).map((ad) => <AdCard key={`home-${ad.id}`} ad={ad} large />)}</div></PreviewSection><PreviewSection title="إعلان بين النتائج" label="نتائج البحث"><div className="space-y-2">{previewAds.slice(0, 3).map((ad) => <AdRow key={`search-${ad.id}`} ad={ad} />)}</div></PreviewSection><PreviewSection title="ظهور داخل القسم" label="صفحة التخصص"><div className="rounded-[20px] border border-[#eadba7] bg-[#fffdf4] p-4 shadow-[0_5px_14px_rgba(14,47,98,0.05)]">{previewAds[0] ? <AdCard ad={previewAds[0]} /> : <Empty text="ستظهر المعاينة عند اعتماد أول إعلان." />}</div></PreviewSection><div className="flex items-center gap-2 rounded-2xl border border-[#dce7f5] bg-[#eef5ff] p-4 text-xs leading-5 text-[#315a86]"><Eye className="h-4 w-4 shrink-0" />يتم تسجيل الظهور والنقر والاتصال وواتساب لتمكين المهني من قياس أثر الإعلان.</div></div></main>;
}
function PreviewSection({ title, label, children }: { title: string; label: string; children: ReactNode }) { return <section><div className="mb-3 flex items-center justify-between"><span className="rounded-full bg-[#f5b916]/15 px-2 py-1 text-[10px] font-bold text-[#8c6b00]">{label}</span><h2 className="text-[15px] font-black">{title}</h2></div>{children}</section>; }
function Empty({ text }: { text: string }) { return <div className="rounded-2xl border border-dashed border-[#cbd5e1] bg-white p-6 text-center text-xs text-[#708198]">{text}</div>; }
function AdCard({ ad, large = false }: { ad: any; large?: boolean }) { const vip = ad.plan === "vip"; return <article className={`overflow-hidden rounded-[22px] border-2 ${vip ? "border-[#0e2f62]" : "border-[#eadba7]"} bg-[#fffdf4] shadow-[0_8px_20px_rgba(14,47,98,0.09)] ${large ? "min-h-[150px]" : ""}`}><div className="relative">{ad.imageUrl ? <img src={ad.imageUrl} alt="" className="h-32 w-full object-cover" /> : <div className="flex h-20 items-center justify-center bg-gradient-to-l from-[#fff5db] to-[#eef2f6]"><Megaphone className="h-8 w-8 text-[#f5b916]" /></div>}<div className="absolute right-3 top-3"><SponsoredBadge vip={vip} /></div></div><div className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-black">{ad.title}</p><p className="mt-1 flex items-center gap-1 truncate text-[11px] text-[#708198]"><span>{ad.providerName || "مهني موصى به"}</span>{ad.city && <><span>·</span><MapPin className="h-3 w-3" />{ad.city}</>}</p></div></div>{ad.description && <p className="mt-3 line-clamp-2 text-[11px] leading-5 text-[#60728a]">{ad.description}</p>}<div className="mt-4 flex gap-2"><Link href={`/providers/${ad.providerId}`} onClick={() => track(ad.id, "click")} className="flex-1 rounded-xl bg-[#0e2f62] py-2 text-center text-[11px] font-black text-white">عرض الملف</Link>{ad.providerPhone && <a href={`tel:${ad.providerPhone}`} onClick={() => track(ad.id, "call")} className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#eaf5ed] text-[#16833b]" aria-label="اتصال"><Phone className="h-4 w-4" /></a>}{ad.providerPhone && <a href={`https://wa.me/${String(ad.providerPhone).replace(/[^0-9+]/g, "").replace(/^\+/, "")}`} target="_blank" rel="noreferrer" onClick={() => track(ad.id, "whatsapp")} className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#eaf5ed] text-[#16833b]" aria-label="واتساب">W</a>}</div></div></article>; }
function AdRow({ ad }: { ad: any }) { return <article className="flex items-center gap-3 rounded-[17px] border-2 border-[#eadba7] bg-[#fffdf4] p-3 shadow-[0_5px_14px_rgba(14,47,98,0.06)]"><div className="flex h-11 w-11 shrink-0 items-center justify-center overflow-hidden rounded-2xl bg-[#fff5db] text-[#8c6b00]">{ad.imageUrl ? <img src={ad.imageUrl} alt="" className="h-full w-full object-cover" /> : <Megaphone className="h-5 w-5" />}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-black">{ad.title}</p><p className="mt-1 truncate text-[11px] text-[#708198]">{ad.providerName || "مهني موصى به"} · {ad.categoryName || "خدمات متنوعة"}</p></div><SponsoredBadge vip={ad.plan === "vip"} /></article>; }
