import { useEffect, useState } from "react";
import { Plus, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useToast } from "@/hooks/use-toast";
import { apiRequest } from "@/lib/auth";

type Taxonomy = { id: number; name: string; icon: string; specializations: Array<{ id: number; name: string; isActive: boolean; services: Array<{ id: number; name: string; isActive: boolean }> }> };
export default function AdminTaxonomy() {
  const [items, setItems] = useState<Taxonomy[]>([]); const [category, setCategory] = useState(""); const [specialization, setSpecialization] = useState<Record<number, string>>({}); const [service, setService] = useState<Record<number, string>>({}); const { toast } = useToast();
  const load = () => apiRequest("/taxonomy").then(setItems).catch((e) => toast({ title: "تعذر تحميل التصنيفات", description: e.message, variant: "destructive" }));
  useEffect(() => { load(); }, []);
  const create = async (path: string, body: object) => { try { await apiRequest(path, { method: "POST", body: JSON.stringify(body) }); toast({ title: "تمت الإضافة" }); load(); } catch (e) { toast({ title: "تعذر الحفظ", description: e instanceof Error ? e.message : "حاول مرة أخرى", variant: "destructive" }); } };
  return <div className="p-6" dir="rtl"><div className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-black">إدارة التخصصات والمهن</h1><p className="mt-1 text-sm text-muted-foreground">أضف وعدّل الأقسام والتخصصات والخدمات دون تحديث التطبيق.</p></div><Button variant="outline" onClick={load}><RefreshCw className="ml-2 h-4 w-4" />تحديث</Button></div><div className="mb-6 flex gap-2"><Input value={category} onChange={(e) => setCategory(e.target.value)} placeholder="اسم قسم جديد" /><Button onClick={() => { if (category.trim()) create("/categories", { name: category.trim(), icon: "🔧" }); setCategory(""); }}><Plus className="ml-2 h-4 w-4" />إضافة قسم</Button></div><div className="space-y-4">{items.map((item) => <section key={item.id} className="rounded-2xl border border-border bg-card p-5"><h2 className="text-lg font-black">{item.icon} {item.name}</h2><div className="mt-4 space-y-3 pr-4">{item.specializations.map((spec) => <div key={spec.id} className="rounded-xl bg-muted/50 p-3"><div className="flex items-center justify-between"><b>{spec.name}</b><span className="text-xs text-muted-foreground">{spec.services.length} خدمات</span></div><div className="mt-2 flex flex-wrap gap-2">{spec.services.map((itemService) => <span key={itemService.id} className="rounded-lg border border-border bg-background px-2 py-1 text-xs">{itemService.name}</span>)}</div><div className="mt-3 flex gap-2"><Input value={specialization[item.id] ?? ""} onChange={(e) => setSpecialization((old) => ({ ...old, [item.id]: e.target.value }))} placeholder="تخصص جديد داخل القسم" /><Button size="sm" onClick={() => { const value = specialization[item.id]?.trim(); if (value) create("/admin/specializations", { categoryId: item.id, name: value }); }}><Plus className="ml-1 h-3 w-3" />تخصص</Button><Input value={service[spec.id] ?? ""} onChange={(e) => setService((old) => ({ ...old, [spec.id]: e.target.value }))} placeholder="خدمة جديدة" /><Button size="sm" onClick={() => { const value = service[spec.id]?.trim(); if (value) create("/admin/services", { specializationId: spec.id, name: value }); }}><Plus className="ml-1 h-3 w-3" />خدمة</Button></div></div>)}</div></section>)}</div></div>;
}
